---
title: "Plotly"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

## Plotly!!!!! Your guess is as good as mine

```{r }
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
set.seed(1)

data(nyc_airbnb)
nyc_abnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```

```{r}
nyc_abnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

```{r}
nyc_abnb %>% 
  mutate(neighbourhood=fct_reorder(neighbourhood,price)) %>% 
  plot_ly(
    y = ~price, type = "box", mode = "markers",
    color = ~neighbourhood)

```

```{r}
nyc_abnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```





























